'use client';
import Link from 'next/link';
import { useState } from 'react';
import { request } from '@/lib/api';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Card,CardContent } from '@/components/ui/card';
import { useSession } from './session';
import { clerkConfigured } from '@/lib/clerk-config';
export function AccountSecurity(){const {user,refresh}=useSession();const [busy,setBusy]=useState(false);const [error,setError]=useState('');return <Card className="account-security"><CardContent><span className="kicker">A LITTLE PEACE OF MIND</span><h2>Sign-in & security</h2><p>{user?.emailVerified?'Your email is verified.':'Verify your email to secure this account.'} Changing your password signs out all sessions.</p>{user?.hasPassword?<form className="product-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{if(f.get('password')!==f.get('confirmation'))throw new Error('The passwords do not match.');await request('/auth/change-password',{method:'POST',body:JSON.stringify({currentPassword:f.get('currentPassword'),password:f.get('password')})});await refresh();}catch(e){setError(e instanceof Error?e.message:'Could not update password.');}finally{setBusy(false);}}}><label>Current password<Input type="password" name="currentPassword" autoComplete="current-password" required maxLength={72}/></label><label>New password<Input type="password" name="password" autoComplete="new-password" required minLength={12} maxLength={72}/></label><label>Confirm new password<Input type="password" name="confirmation" autoComplete="new-password" required minLength={12} maxLength={72}/></label><Button disabled={busy}>{busy?'Updating…':'Change password & sign out'}</Button>{error&&<p className="form-error" role="alert">{error}</p>}</form>:<Button asChild variant="outline"><Link href="/forgot-password">Set an email password</Link></Button>}<div className="social-settings"><p>{user?.socialLinked?'Your social identity is linked to this workspace.':'Link a verified social identity with the same email to this workspace.'}</p>{clerkConfigured()&&<Button variant="outline" asChild><Link href="/oauth">{user?.socialLinked?'Use social sign-in':'Link social sign-in'}</Link></Button>}</div></CardContent></Card>;}
