'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { MailCheck,KeyRound,CheckCircle2 } from 'lucide-react';
import { request } from '@/lib/api';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Brand } from './brand';
import { useSession } from './session';
export function AccountRecovery({mode}:{mode:'forgot'|'reset'|'verify'}){
 const [token,setToken]=useState('');const [ready,setReady]=useState(mode==='forgot');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const {refresh}=useSession();
 useEffect(()=>{if(mode!=='forgot'){setToken(new URLSearchParams(window.location.hash.slice(1)).get('token')||'');setReady(true);window.history.replaceState(null,'',window.location.pathname);}},[mode]);
 const title=mode==='forgot'?'A fresh start.':mode==='reset'?'Make it yours again.':'One small confirmation.';
 return <main className="account-flow"><Brand/><section className="account-flow-card"><div className="flow-symbol">{message?<CheckCircle2/>:mode==='verify'?<MailCheck/>:<KeyRound/>}</div><span className="kicker">YOUR NEXT GOOD IDEA IS WAITING</span><h1>{title}</h1><p>{mode==='forgot'?'Enter your account email and we’ll send a secure reset link.':mode==='reset'?'Choose a new password. This signs out your other sessions.':'Confirm your email to unlock your workspace. Nothing is confirmed until you press the button.'}</p>{message?<div className="success-note" role="status">{message}</div>:<form className="product-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const body=mode==='forgot'?{email:f.get('email')}:mode==='reset'?{token,password:f.get('password')}:{token};if(mode==='reset'&&f.get('password')!==f.get('confirmation'))throw new Error('The passwords do not match.');const result=await request<{message:string}>(mode==='forgot'?'/auth/forgot-password':mode==='reset'?'/auth/reset-password':'/auth/verify-email',{method:'POST',body:JSON.stringify(body)});setMessage(result.message);if(mode==='verify')await refresh();}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}}>
 {mode==='forgot'&&<label>Email address<Input name="email" type="email" required maxLength={254} autoComplete="email" placeholder="you@yourteam.com"/></label>}
 {mode==='reset'&&<><label>New password<Input name="password" type="password" required minLength={12} maxLength={72} autoComplete="new-password"/></label><label>Confirm password<Input name="confirmation" type="password" required minLength={12} maxLength={72} autoComplete="new-password"/></label><small>At least 12 characters. A memorable phrase works well.</small></>}
 {ready&&mode!=='forgot'&&!token&&<p className="form-error">Open the complete link from your email. To get a new link, {mode==='reset'?<Link href="/forgot-password">request a password reset</Link>:<Link href="/login">sign in and resend verification</Link>}.</p>}
 {error&&<p className="form-error" role="alert">{error}</p>}<Button disabled={busy||!ready||(mode!=='forgot'&&!token)}>{busy?'Working…':mode==='forgot'?'Send reset link':mode==='reset'?'Update password':'Verify my email'}</Button></form>}
 {message&&<Button asChild><Link href={mode==='verify'?'/app':'/login'}>{mode==='verify'?'Open workspace':'Back to sign in'}</Link></Button>}<Link href="/login" className="flow-back">← Back to sign in</Link><p className="flow-help">Need a hand? <Link href="/contact">Contact support</Link></p></section></main>;
}
export function VerificationGate(){const {user,refresh}=useSession();const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');return <main className="account-flow"><Brand/><section className="account-flow-card"><div className="flow-symbol"><MailCheck/></div><span className="kicker">A WORKSPACE THAT IS TRULY YOURS</span><h1>Check your inbox.</h1><p>Open the verification email sent to <strong>{user?.email}</strong>. Then return here to continue.</p><div className="flow-actions"><Button disabled={busy} onClick={async()=>{setBusy(true);try{await refresh();}finally{setBusy(false);}}}>I’ve verified my email</Button><Button variant="outline" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await request<{message:string}>('/auth/resend-verification',{method:'POST'});setMessage(r.message);}catch(e){setMessage(e instanceof Error?e.message:'Try again.');}finally{setBusy(false);}}}>Resend email</Button></div>{message&&<p role="status">{message}</p>}<Button variant="ghost" disabled={busy} onClick={async()=>{setBusy(true);try{await request('/auth/logout',{method:'POST'});await refresh();}catch(e){setMessage(e instanceof Error?e.message:'Try again.');}finally{setBusy(false);}}}>Use another account</Button></section></main>;}
