'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { ShieldCheck,Users,FileText,CreditCard,History,ArrowUpRight,Save,LoaderCircle,Plus,Trash2 } from 'lucide-react';
import { request } from '@/lib/api';
import type { Plan } from '@/lib/product';
import { policies,type Policy } from '@/lib/legal-content';
import { siteFields,type SiteSnapshot } from '@/lib/site-fields';
import { Button } from '@/components/ui/button';
import { Card,CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Switch } from '@/components/ui/switch';
import { Modal } from '@/components/modal';
import { useSession } from './session';
import { useSite } from './site-provider';

const pages=[['/app/admin','Overview',ShieldCheck],['/app/admin-content','Site content',FileText],['/app/admin-plans','Plans & limits',CreditCard],['/app/admin-users','Accounts',Users],['/app/admin-audit','Audit log',History]] as const;
function Feedback({error,success}:{error:string;success?:string}){return <>{error&&<p role="alert" className="form-error">{error}</p>}{success&&<p role="status" className="success-note">{success}</p>}</>;}
function message(e:unknown){return e instanceof Error?e.message:'Something went wrong. Please try again.';}
export function AdminPanel({section}:{section:string}){
 const {user}=useSession();
 if(user?.role!=='ADMIN')return <div className="access-note"><ShieldCheck size={36}/><h1>Administrator access required.</h1><p>Your workspace is still available. This area is for authorised site administrators.</p><Button asChild><Link href="/app">Return to your workspace</Link></Button></div>;
 return <><div className="page-heading"><div><span className="kicker">THE CARE BEHIND THE COMMON GROUND</span><h1>Administration.</h1><p>Manage the public site and accounts. Every saved change is recorded.</p></div><span className="admin-role"><ShieldCheck size={15}/>Administrator</span></div><nav className="admin-nav" aria-label="Administration pages">{pages.map(([href,label,Icon])=><Link href={href} key={href} className={href===`/app/${section}`?'current':''}><Icon size={15}/>{label}</Link>)}</nav>{section==='admin-content'?<ContentEditor/>:section==='admin-plans'?<PlansEditor/>:section==='admin-users'?<AccountsEditor/>:section==='admin-audit'?<AuditLog/>:<AdminOverview/>}</>;
}
function AdminOverview(){
 const [stats,setStats]=useState<Record<string,number>|null>(null);const [error,setError]=useState('');useEffect(()=>{request<Record<string,number>>('/admin/overview').then(setStats).catch(e=>setError(message(e)));},[]);
 return <><Feedback error={error}/><div className="admin-stats">{['accounts','members','rooms','bookings'].map(label=><Card key={label}><CardContent><span>{label}</span><strong>{stats?stats[label]:'…'}</strong></CardContent></Card>)}</div><div className="tool-grid">{pages.slice(1).map(([href,label,Icon])=><Link href={href} key={href} className="tool-card"><Icon size={27}/><h2>{label}</h2><p>{label==='Site content'?'Edit branding, contact details, public page copy, and policies.':label==='Plans & limits'?'Update the three plans and the limits the backend enforces.':label==='Accounts'?'Find an account, edit its details, and manage access.':'Review who changed the site and when.'}</p><span>Open page<ArrowUpRight size={16}/></span></Link>)}</div><p className="tool-note">Administrators can operate the site and use their own workspace without plan caps. Regular users manage only their own workspace. The protected owner account cannot be demoted or suspended from this panel.</p></>;
}
function ContentEditor(){
 const site=useSite();const [document,setDocument]=useState<SiteSnapshot|null>(null);const [group,setGroup]=useState('Brand');const [policySlug,setPolicySlug]=useState('privacy');const [error,setError]=useState('');const [success,setSuccess]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{request<SiteSnapshot>('/site').then(setDocument).catch(e=>setError(message(e)));},[]);
 const set=(key:string,value:string)=>{setDocument(old=>old?{...old,values:{...old.values,[key]:value}}:old);setSuccess('');};
 const remove=(key:string)=>{setDocument(old=>{if(!old)return old;const values={...old.values};delete values[key];return {...old,values};});setSuccess('');};
 async function save(){if(!document)return;setBusy(true);setError('');setSuccess('');try{const saved=await request<SiteSnapshot>('/admin/site',{method:'PUT',body:JSON.stringify(document)});setDocument(saved);site.update(saved);setSuccess('Site content published. Open a page to see the changes.');}catch(e){setError(message(e));}finally{setBusy(false);}}
 let policy:Policy=policies[policySlug];try{if(document?.values[`policy.${policySlug}`])policy=JSON.parse(document.values[`policy.${policySlug}`]);}catch{}
 return <><Feedback error={error} success={success}/>{!document?<p className="page-loading">Loading site content…</p>:<Card className="admin-editor"><CardContent><div className="editor-heading"><div><h2>Make the site yours.</h2><p>Changes publish when you save. Blank custom text stays blank; “Use default” removes an override.</p></div><Button disabled={busy} onClick={()=>void save()}>{busy?<LoaderCircle size={15} className="spin"/>:<Save size={15}/>}Save all changes</Button></div><div className="editor-groups" role="group" aria-label="Content groups">{['Brand','Homepage','Pages','Pricing','Policies'].map(name=><Button key={name} variant={group===name?'default':'outline'} size="sm" onClick={()=>setGroup(name)}>{name}</Button>)}</div><fieldset disabled={busy} className="editor-fields">{group!=='Policies'?siteFields.filter(([section])=>section===group).map(([,key,label,fallback])=><div className="cms-field" key={key}><Label htmlFor={`cms-${key}`}>{label}</Label>{fallback.length>85?<Textarea id={`cms-${key}`} rows={3} value={document.values[key]??fallback} maxLength={2000} onChange={e=>set(key,e.target.value)}/>:<Input id={`cms-${key}`} value={document.values[key]??fallback} maxLength={key==='brand.companyUrl'?500:300} onChange={e=>set(key,e.target.value)}/>}<button className="reset-field" type="button" onClick={()=>remove(key)} disabled={document.values[key]===undefined}>Use default</button></div>):<><Label htmlFor="policy-choice">Policy page</Label><select id="policy-choice" value={policySlug} onChange={e=>setPolicySlug(e.target.value)}>{Object.entries(policies).map(([key,value])=><option value={key} key={key}>{value.title}</option>)}</select><PolicyEditor key={policySlug} policy={policy} onChange={p=>set(`policy.${policySlug}`,JSON.stringify(p))}/><Button variant="outline" onClick={()=>remove(`policy.${policySlug}`)}>Restore this policy’s default copy</Button></>}</fieldset><p className="tool-note">Contact and branding values update across the site. Policy sections use plain text and are rendered safely. Layout and application logic remain in code.</p></CardContent></Card>}</>;
}
function PolicyEditor({policy,onChange}:{policy:Policy;onChange:(policy:Policy)=>void}){
 const section=(index:number,patch:Partial<Policy['sections'][number]>)=>onChange({...policy,sections:policy.sections.map((s,i)=>i===index?{...s,...patch}:s)});
 return <div className="policy-editor">{(['title','description','summary'] as const).map(field=><label key={field}>{field}<Textarea rows={2} value={policy[field]} onChange={e=>onChange({...policy,[field]:e.target.value})}/></label>)}{policy.sections.map((s,index)=><div className="policy-edit-section" key={s.id}><div><strong>Section {index+1}</strong><Button variant="ghost" size="sm" onClick={()=>onChange({...policy,sections:policy.sections.filter((_,i)=>i!==index)})} aria-label={`Remove section ${index+1}`}><Trash2 size={15}/></Button></div><label>Heading<Input value={s.title} onChange={e=>section(index,{title:e.target.value})}/></label><label>Paragraphs · separate with a blank line<Textarea rows={6} value={s.paragraphs.join('\n\n')} onChange={e=>section(index,{paragraphs:e.target.value.split('\n\n')})}/></label><label>Bullet points · one per line<Textarea rows={3} value={s.points?.join('\n')||''} onChange={e=>section(index,{points:e.target.value?e.target.value.split('\n'):undefined})}/></label></div>)}<Button variant="outline" onClick={()=>onChange({...policy,sections:[...policy.sections,{id:`section-${Date.now()}`,title:'New section',paragraphs:['']} ]})}><Plus size={16}/>Add section</Button></div>;
}
function PlansEditor(){
 const [plans,setPlans]=useState<Plan[]>([]);const [error,setError]=useState('');const [success,setSuccess]=useState('');const [busy,setBusy]=useState('');useEffect(()=>{request<Plan[]>('/plans').then(setPlans).catch(e=>setError(message(e)));},[]);
 function edit(id:string,patch:Partial<Plan>){setPlans(old=>old.map(p=>p.id===id?{...p,...patch}:p));setSuccess('');}
 async function save(plan:Plan){setBusy(plan.id);setError('');setSuccess('');try{const saved=await request<Plan>(`/admin/plans/${plan.id}`,{method:'PUT',body:JSON.stringify(plan)});edit(plan.id,saved);setSuccess(`${saved.name} updated. Align its Stripe monthly price before enabling checkout.`);}catch(e){setError(message(e));}finally{setBusy('');}}
 return <><Feedback error={error} success={success}/><p className="tool-note">These values control the live pricing cards and backend limits. Stripe Price IDs stay in the backend environment. Checkout verifies the amount and currency before charging.</p><div className="admin-plan-grid">{plans.map(plan=><Card key={plan.id}><CardContent><form className="product-form" onSubmit={e=>{e.preventDefault();void save(plan);}}><Label htmlFor={`plan-${plan.id}`}>Plan name</Label><Input id={`plan-${plan.id}`} value={plan.name} required maxLength={80} onChange={e=>edit(plan.id,{name:e.target.value})}/><label>Currency<select value={plan.currency} onChange={e=>edit(plan.id,{currency:e.target.value})}><option value="INR">INR · Indian rupee</option><option value="USD">USD · US dollar</option></select></label><label>Description<Textarea required maxLength={300} value={plan.description} onChange={e=>edit(plan.id,{description:e.target.value})}/></label>{([['monthlyPrice','Price / month',10000],['members','People',10000],['rooms','Rooms',1000],['bookings','Weekly bookings',100000],['presets','Meeting presets',1000]] as const).map(([field,label,max])=><label key={field}>{label}<Input type="number" min={1} max={max} required value={plan[field]} onChange={e=>edit(plan.id,{[field]:Number(e.target.value)})}/></label>)}<Button type="submit" disabled={!!busy}>{busy===plan.id?<LoaderCircle className="spin" size={15}/>:<Save size={15}/>}Save {plan.name}</Button></form></CardContent></Card>)}</div></>;
}
type AdminAccount={id:string;email:string;name:string;workspaceName:string;timezone:string;role:'USER'|'ADMIN';suspended:boolean;plan:string;subscribed:boolean};
type AccountPage={items:AdminAccount[];total:number;pages:number;page:number};
function AccountsEditor(){
 const {user}=useSession();const [result,setResult]=useState<AccountPage|null>(null);const [query,setQuery]=useState('');const [search,setSearch]=useState('');const [page,setPage]=useState(0);const [editing,setEditing]=useState<AdminAccount|null>(null);const [error,setError]=useState('');const [success,setSuccess]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;setResult(null);request<AccountPage>(`/admin/users?q=${encodeURIComponent(search)}&page=${page}`).then(data=>{if(active)setResult(data);}).catch(e=>{if(active)setError(message(e));});return()=>{active=false;};},[search,page]);
 async function save(){if(!editing)return;setBusy(true);setError('');try{const saved=await request<AdminAccount>(`/admin/users/${editing.id}`,{method:'PUT',body:JSON.stringify(editing)});setResult(old=>old?{...old,items:old.items.map(a=>a.id===saved.id?saved:a)}:old);setEditing(null);setSuccess('Account updated. Role and suspension changes apply to existing sessions.');}catch(e){setError(message(e));}finally{setBusy(false);}}
 return <><Feedback error={editing?'':error} success={success}/><form className="admin-search" onSubmit={e=>{e.preventDefault();setPage(0);setSearch(query);setError('');}}><Input aria-label="Search accounts by name or email" placeholder="Search name or email" value={query} onChange={e=>setQuery(e.target.value)} maxLength={254}/><Button type="submit" variant="outline">Find accounts</Button></form><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Account</th><th>Workspace</th><th>Role</th><th>Status</th><th>Plan</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{result?.items.map(a=><tr key={a.id}><td><strong>{a.name}</strong><small>{a.email}</small></td><td>{a.workspaceName}</td><td>{a.role}</td><td><span className={a.suspended?'status-paused':'status-active'}>{a.suspended?'Suspended':'Active'}</span></td><td>{a.plan==='free'?'Preview':a.plan}</td><td><Button size="sm" variant="outline" onClick={()=>{setError('');setEditing(a);}}>Edit</Button></td></tr>)}</tbody></table>{!result&&!error&&<p className="page-loading">Loading accounts…</p>}{result&&!result.items.length&&<p className="page-loading">No accounts match this search.</p>}</div><div className="admin-pagination"><span>{result?.total??0} accounts</span><Button size="sm" variant="outline" disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</Button><span>Page {page+1}</span><Button size="sm" variant="outline" disabled={!result||page+1>=result.pages} onClick={()=>setPage(p=>p+1)}>Next</Button></div>{editing&&<Modal title="Manage account" subtitle={editing.email} onClose={()=>setEditing(null)} busy={busy}><Feedback error={error}/><form className="product-form" onSubmit={e=>{e.preventDefault();void save();}}>{(['name','workspaceName','timezone'] as const).map(field=><label key={field}>{field==='workspaceName'?'Workspace':field==='timezone'?'Timezone':'Display name'}<Input required value={editing[field]} maxLength={field==='workspaceName'?100:80} onChange={e=>setEditing({...editing,[field]:e.target.value})}/></label>)}<label>Role<select value={editing.role} disabled={editing.id===user?.id} onChange={e=>setEditing({...editing,role:e.target.value as 'USER'|'ADMIN'})}><option value="USER">User — own workspace only</option><option value="ADMIN">Admin — site and account management</option></select></label><div className="switch-field"><Label htmlFor="suspend-account">Suspend sign-in and existing sessions</Label><Switch id="suspend-account" disabled={editing.id===user?.id} checked={editing.suspended} onCheckedChange={value=>setEditing({...editing,suspended:value})}/></div><p className="field-note">Administrator access includes editing public content, plans, and other accounts. Subscription billing stays managed by the payment provider.</p><Button disabled={busy} type="submit">Save account changes</Button></form></Modal>}</>;
}
function AuditLog(){
 const [events,setEvents]=useState<{id:string;action:string;target:string;actorId:string;occurredAt:string}[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(true);useEffect(()=>{request<typeof events>('/admin/audit').then(setEvents).catch(e=>setError(message(e))).finally(()=>setLoading(false));},[]);
 return <><Feedback error={error}/><p className="tool-note">The latest 100 administrative changes. Times are shown in your browser’s timezone.</p><div className="audit-list">{events.map(event=><article key={event.id}><History size={18}/><div><strong>{event.action}</strong><p>{event.target}</p><small>Administrator ID: {event.actorId}</small></div><time dateTime={event.occurredAt}>{new Date(event.occurredAt).toLocaleString()}</time></article>)}{loading?<p className="page-loading">Loading the audit trail…</p>:!events.length&&<p className="page-loading">Saved administrative changes will appear here.</p>}</div></>;
}
