"use client";
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { motion,useReducedMotion } from 'motion/react';
import { ArrowUpRight,Users,DoorOpen,CalendarDays,Clock3,Download,Plus,Check } from 'lucide-react';
import { api } from '@/lib/api';
import { DAYS,dayName,range,minutes,type Member,type Room,type Booking } from '@/lib/types';
import { Button } from '@/components/ui/button';
import { Card,CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { ConfirmAction } from '@/components/workspace-editors';
import { useSession } from './session';

function calendarFile(bookings:Booking[],timezone:string){
 const escape=(s:string)=>s.replaceAll('\\','\\\\').replaceAll('\n','\\n').replaceAll(',','\\,').replaceAll(';','\\;');
 const parts=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());
 const part=(type:string)=>parts.find(p=>p.type===type)!.value;
 const today=new Date(`${part('year')}-${part('month')}-${part('day')}T00:00:00Z`);
 const stamp=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');
 const events=bookings.map(b=>{const date=new Date(today);date.setUTCDate(date.getUTCDate()+((DAYS.indexOf(b.dayOfWeek)+1-date.getUTCDay()+7)%7));const d=date.toISOString().slice(0,10).replaceAll('-','');return ['BEGIN:VEVENT',`UID:${b.id}@meetgrid`,`DTSTAMP:${stamp}`,`DTSTART;TZID=${timezone}:${d}T${b.startTime.slice(0,5).replace(':','')}00`,`DTEND;TZID=${timezone}:${d}T${b.endTime.slice(0,5).replace(':','')}00`,`RRULE:FREQ=WEEKLY;BYDAY=${b.dayOfWeek.slice(0,2)}`,`SUMMARY:${escape(b.roomName)} — team meeting`,'END:VEVENT'].join('\r\n');});
 const blob=new Blob([['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//MeetGrid//Weekly bookings//EN','CALSCALE:GREGORIAN',...events,'END:VCALENDAR'].join('\r\n')],{type:'text/calendar;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='meetgrid-bookings.ics';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export function Dashboard({mode='overview'}:{mode?:'overview'|'bookings'|'insights'}){
 const {user}=useSession();const reduced=useReducedMotion();const [members,setMembers]=useState<Member[]>([]);const [rooms,setRooms]=useState<Room[]>([]);const [bookings,setBookings]=useState<Booking[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [cancel,setCancel]=useState<Booking|null>(null);
 useEffect(()=>{let active=true;Promise.all([api.members(),api.rooms(),api.bookings()]).then(([m,r,b])=>{if(active){setMembers(m);setRooms(r);setBookings(b);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
 const weeklyHours=bookings.reduce((s,b)=>s+(minutes(b.endTime)-minutes(b.startTime))/60,0);
 const totalHours=rooms.reduce((s,r)=>s+(minutes(r.closeTime)-minutes(r.openTime))*7/60,0);
 const coverage=members.filter(m=>m.availability.length>0).length;
 if(loading)return <p className="page-loading" role="status">Getting your workspace ready…</p>;
 if(error)return <p className="form-error" role="alert">{error}</p>;
 return <><div className="page-heading"><div><span className="kicker">{mode==='overview'?'A LITTLE CLARITY FOR YOUR DAY':mode==='bookings'?'EVERY RESERVATION, IN ONE PLACE':'THE SHAPE OF YOUR WEEK'}</span><h1>{mode==='overview'?`Hello, ${user?.name.split(' ')[0] || 'there'}.`:mode==='bookings'?'Your week, reserved.':'Make room for better decisions.'}</h1><p>{mode==='overview'?`Here's what's taking shape at ${user?.workspaceName}.`:mode==='bookings'?'Recurring weekly bookings, in your workspace timezone.':'Real numbers from your saved rooms and recurring bookings.'}</p></div><Button asChild><Link href="/app/planner"><Plus size={16}/>Plan a meeting</Link></Button></div>
 {mode==='overview'&&<section className="welcome-banner"><div><span className="kicker">BRING YOUR NEXT IDEA TOGETHER</span><h2>People. Place.<br/><span className="serif-word">A little common ground.</span></h2><p>Your next meeting starts with a shared free hour.</p><Link href="/app/planner">Find your next meeting<ArrowUpRight size={18}/></Link></div><div className="banner-art" aria-hidden="true"><span className="tile-people"><Users size={48}/></span><span className="tile-plus">+</span><span className="tile-place"><DoorOpen size={48}/></span><span className="tile-check"><Check size={25}/></span></div></section>}
 <div className="metric-grid">{[{label:'People in your team',value:members.length,detail:`${coverage} with availability`,Icon:Users,tone:'purple'},{label:'Spaces to meet',value:rooms.length,detail:'Customized for your workspace',Icon:DoorOpen,tone:'pink'},{label:'Weekly bookings',value:bookings.length,detail:'Active recurring reservations',Icon:CalendarDays,tone:'yellow'},{label:'Hours together',value:Math.round(weeklyHours*10)/10,detail:'Room hours reserved per week',Icon:Clock3,tone:'green'}].map(({label,value,detail,Icon,tone})=><motion.div key={label} whileHover={reduced?{}:{y:-3}}><Card className={`metric-card ${tone}`}><CardContent><div><span>{label}</span><Icon size={18}/></div><strong>{value}</strong><small>{detail}</small></CardContent></Card></motion.div>)}</div>
 {mode==='overview'&&(!members.length||!rooms.length||coverage<members.length)&&<section className="onboarding-card"><div><span className="kicker">MAKE YOURSELF AT HOME</span><h2>Three small steps. One calmer week.</h2></div><div className="setup-steps">{[{done:members.length>0,title:'Add your people',link:'/app/planner',body:'Names, colors, and a team that is yours.'},{done:coverage>0&&coverage===members.length,title:'Set availability',link:'/app/planner',body:'Choose the weekly times each person is free.'},{done:rooms.length>0,title:'Add your spaces',link:'/app/rooms',body:'Room names, seats, and opening hours.'}].map((s,i)=><Link key={s.title} href={s.link}><span className={s.done?'step-done':''}>{s.done?<Check size={17}/>:i+1}</span><div><strong>{s.title}</strong><p>{s.body}</p></div><ArrowUpRight size={17}/></Link>)}</div></section>}
 {mode==='insights'?<section className="data-panel"><div className="section-top"><div><h2>Room utilization</h2><p>{totalHours?Math.round(weeklyHours/totalHours*100):0}% of configured weekly opening hours are reserved.</p></div><Badge>Based on your bookings</Badge></div>{!rooms.length?<p className="panel-empty">Add rooms and make bookings to see your workspace take shape.</p>:rooms.map(room=>{const used=bookings.filter(b=>b.roomId===room.id).reduce((s,b)=>s+minutes(b.endTime)-minutes(b.startTime),0);const open=(minutes(room.closeTime)-minutes(room.openTime))*7;const percent=open?Math.round(used/open*100):0;return <div className="utilization-row" key={room.id}><div><strong>{room.name}</strong><span>{Math.round(used/6)/10} reserved hours · {percent}%</span></div><div className="utilization-track"><motion.div initial={false} animate={{width:`${Math.min(percent,100)}%`}} transition={{type:'spring',stiffness:120,damping:25}}/></div></div>;})}<p className="insight-note">Utilization uses the same daily opening hours across all seven days. These are scheduled hours, not measured attendance.</p></section>:<section className="data-panel"><div className="section-top"><div><span className="kicker">A PLACE ON THE CALENDAR</span><h2>Weekly bookings</h2></div><Button variant="outline" disabled={!bookings.length} onClick={()=>calendarFile(bookings,user?.timezone||'UTC')}><Download size={15}/>Export calendar</Button></div>{!bookings.length?<div className="panel-empty"><CalendarDays size={30}/><h3>Your next get-together goes here.</h3><p>Find a shared free slot and book a room. Your reservations will appear here.</p><Button asChild variant="outline"><Link href="/app/planner">Find a meeting<ArrowUpRight size={16}/></Link></Button></div>:<div className="booking-table">{DAYS.filter(day=>bookings.some(b=>b.dayOfWeek===day)).map(day=><div className="booking-day" key={day}><h3>{dayName(day)}</h3>{bookings.filter(b=>b.dayOfWeek===day).map(b=><div className="booking-line" key={b.id}><span className="booking-room-icon"><DoorOpen size={18}/></span><div><strong>{b.roomName}</strong><span>{range(b.startTime,b.endTime)}</span></div><Badge>Weekly</Badge><Button variant="ghost" size="sm" onClick={()=>setCancel(b)}>Cancel</Button></div>)}</div>)}</div>}</section>}
 {cancel&&<ConfirmAction title="Cancel weekly reservation?" description={`${cancel.roomName} · ${dayName(cancel.dayOfWeek)} · ${range(cancel.startTime,cancel.endTime)}. This releases the recurring slot.`} label="Cancel reservation" onClose={()=>setCancel(null)} action={async()=>{await api.cancelBooking(cancel.id);setBookings(old=>old.filter(b=>b.id!==cancel.id));}}/>}
 </>;
}
