"use client";
import Link from 'next/link';
import { motion,useReducedMotion } from 'motion/react';
import { ArrowRight,ArrowUpRight,Check,CalendarDays,DoorOpen,Users,MoveUpRight,Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card,CardContent } from '@/components/ui/card';
import { BorderBeam } from '@/components/ui/border-beam';
import { Brand } from './brand';
import { product } from '@/lib/product';
import { useSession } from './session';
export function PublicNav(){const {user}=useSession();return <><a className="public-skip" href="#main-content">Skip to content</a><header className="public-nav"><Brand/><nav aria-label="Main navigation"><Link href="/#how-it-works">How it works</Link><Link href="/about">About</Link><Link href="/pricing">Pricing</Link><Link href="/help">Help</Link></nav><div><Link href={user?'/app':'/login'}>{user?'My workspace':'Sign in'}</Link><Button asChild><Link href={user?'/app/planner':'/signup'}>{user?'Plan a meeting':'Get started free'}<ArrowUpRight size={16}/></Link></Button></div></header></>;}
export function PublicFooter(){return <footer className="site-footer"><div className="footer-grid"><div className="footer-story"><Brand/><p>{product.tagline}<br/>A little common ground goes a long way.</p><a className="company-signature" href={product.companyUrl}>In association with <strong>{product.companyName}</strong><ArrowUpRight size={14}/></a></div><nav aria-label="Product links"><h2>Make time</h2><Link href="/#how-it-works">How it works</Link><Link href="/pricing">Plans & pricing</Link><Link href="/signup">Create a workspace</Link><Link href="/help">Help centre</Link></nav><nav aria-label="Company links"><h2>Stay connected</h2><Link href="/about">About us</Link><Link href="/contact">Contact</Link><Link href="/security">Security</Link><Link href="/accessibility">Accessibility</Link></nav><nav aria-label="Legal links"><h2>The clear details</h2><Link href="/legal">Legal centre</Link><Link href="/privacy">Privacy policy</Link><Link href="/terms">Terms of service</Link><Link href="/refunds">Refunds & cancellation</Link><Link href="/cookies">Cookie policy</Link></nav></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {product.name}. In association with {product.companyName}.</span><a href={`mailto:${product.supportEmail}`}>{product.supportEmail}</a><a href={`tel:${product.supportPhone.replace(/[^+\d]/g,'')}`}>{product.supportPhone}</a><span className="footer-flower" aria-hidden="true">✳</span></div></footer>;}
export function Landing(){const reduced=useReducedMotion();return <div className="public-site"><PublicNav/><main id="main-content">
 <section className="landing-hero"><div className="hero-copy"><span className="eyebrow-pill"><i/>A LITTLE LESS “WHEN ARE YOU FREE?”</span><h1>Less back-and-forth.<br/>More <span className="serif-word">getting<br/>together.</span><span className="hero-asterisk" aria-hidden="true">✳</span></h1><p>Turn everyone’s availability into a time <em>and</em> a place.<br/>One thoughtful workspace for people who do things together.</p><div className="hero-ctas"><Button asChild><Link href="/signup">Make room for your team<ArrowUpRight size={18}/></Link></Button><Link href="#how-it-works" className="text-cta">Take a little look <ArrowRight size={16}/></Link></div><div className="hero-footnote"><Check size={14}/>Free to start <span>·</span> No card needed <span>·</span> Yours to customize</div></div>
 <div className="hero-composition" aria-label="Illustrative scheduling preview"><div className="orbit-line"/><span className="sketch-star">✧</span><motion.div className="floating-note" animate={reduced?{}:{rotate:[-8,-5,-8],y:[0,-5,0]}} transition={{duration:7,repeat:Infinity,ease:'easeInOut'}}>Less planning.<br/>More doing.<span>↗</span></motion.div><div className="preview-board"><div className="preview-top"><span><i/> THE COMMON GROUND</span><span>Example workspace</span></div><h3>A time for everyone.</h3><p>One search. Every schedule considered.</p><div className="preview-days">{['MON','TUE','WED','THU','FRI'].map((d,i)=><span key={d} className={i===1?'chosen':''}>{d}</span>)}</div><div className="preview-grid">{['Your team','The collaborators','Everyone'].map((n,i)=><div className="preview-row" key={n}><span>{n}</span><div><motion.i className={`preview-bar bar-${i}`} initial={false} animate={reduced?{}:{scaleX:[.95,1,.95]}} transition={{duration:6,repeat:Infinity,delay:i*.6}}>{i===2?'A little common ground':'Available'}</motion.i></div></div>)}</div><div className="preview-match"><span className="space-symbol"><DoorOpen size={23}/></span><div><strong>Your next great meeting</strong><span>A room, a time, and everyone included</span></div><span className="match-check"><Check size={16}/></span></div>{!reduced&&<BorderBeam duration={12} size={90} colorFrom="#C9C2F5" colorTo="#F6B6C9"/>}</div><motion.div className="little-ticket" whileHover={reduced?{}:{rotate:0,y:-5}}><span>THE BEST KIND OF MATCH</span><strong>People + place</strong><span>Consider it coordinated. <Check size={14}/></span></motion.div><span className="art-label">A meeting of minds. And calendars.</span></div></section>
 <div className="purpose-strip"><span>For the people who bring people together</span><strong>Creative studios</strong><i>✳</i><strong>Campus communities</strong><i>✳</i><strong>Shared workspaces</strong><i>✳</i><strong>Small teams</strong></div>
 <section id="how-it-works" className="marketing-section"><div className="section-intro"><span className="kicker">A SMALL CHANGE TO YOUR EVERYDAY</span><h2>The right people.<br/>The right place.<em> Finally, the same time.</em></h2><p>A room calendar tells you what’s empty. A scheduling link tells you who’s free. {product.name} brings both decisions together.</p></div><div className="feature-bento">{[{n:'01',title:'Start with your people.',body:'Add anyone, set their weekly availability, and pick the people joining this meeting.',icon:Users,color:'purple'},{n:'02',title:'Make space for ideas.',body:'Name your rooms. Set their hours and seats. Keep every reservation in one place.',icon:DoorOpen,color:'pink'},{n:'03',title:'Meet in the middle.',body:'Find a time and room that fit everyone. Book it, export it, or save the setup for next time.',icon:CalendarDays,color:'yellow'}].map(({n,title,body,icon:Icon,color})=><motion.div key={n} whileHover={reduced?{}:{y:-5}} transition={{type:'spring',stiffness:300,damping:25}}><Card className={`feature-card ${color}`}><CardContent><div className="feature-top"><span>{n}</span><Icon size={27}/></div><h3>{title}</h3><p>{body}</p><Link href="/signup">Make it yours<MoveUpRight size={17}/></Link></CardContent></Card></motion.div>)}</div></section>
 <section id="made-for" className="usecase-section"><div><span className="kicker">ONE WORKSPACE. MANY WAYS TOGETHER.</span><h2>Your thing.<br/><span className="serif-word">Your rhythm.</span></h2><p>Not just another calendar. A home for the recurring moments that keep your team moving.</p><Button asChild><Link href="/signup">Find your common ground<ArrowRight size={17}/></Link></Button></div><div className="usecase-list">{[['Creative teams','Find a review slot, reserve the studio, save the setup.'],['Student clubs','Plan a committee meeting around classes and room capacity.'],['Coworking hosts','Manage shared spaces, prevent clashes, and see which rooms get used.'],['Small businesses','Give workshops, planning sessions, and weekly check-ins a repeatable home.']].map(([title,text],i)=><article key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div><ArrowUpRight size={20}/></article>)}</div></section>
 <section className="closing-note"><Sparkles size={30}/><h2>Good things need<br/><span className="serif-word">a little common ground.</span></h2><p>Build your workspace in minutes. Make it better every week.</p><Button asChild><Link href="/signup">Start something together<ArrowUpRight size={18}/></Link></Button></section>
 </main><PublicFooter/></div>;}
