"use client";
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { Plus,Clock3,Users,ArrowUpRight,Pencil,Trash2 } from 'lucide-react';
import { request } from '@/lib/api';
import type { Preset } from '@/lib/product';
import { Card,CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';
import { Modal } from '@/components/modal';
import { ConfirmAction } from '@/components/workspace-editors';
export function Presets(){
 const [items,setItems]=useState<Preset[]>([]);const [editing,setEditing]=useState<Preset|'new'|null>(null);const [remove,setRemove]=useState<Preset|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
 useEffect(()=>{request<Preset[]>('/templates').then(setItems).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 return <><div className="page-heading"><div><span className="kicker">GOOD ROUTINES DESERVE A SHORTCUT</span><h1>Your meeting playbook.</h1><p>Save your workshop, review, or weekly check-in setup. Use it in one click.</p></div><Button onClick={()=>setEditing('new')}><Plus size={16}/>New preset</Button></div>{error&&<p className="form-error" role="alert">{error}</p>}{loading?<p role="status">Loading presets…</p>:!items.length?<div className="preset-empty"><span>✳</span><h2>Make the repeatable, effortless.</h2><p>A 30-minute check-in. A two-hour workshop. Create the setups your team comes back to.</p><Button onClick={()=>setEditing('new')}>Create your first preset<ArrowUpRight size={16}/></Button></div>:<div className="preset-grid">{items.map(p=><Card key={p.id} className="preset-card"><CardContent><div className="preset-mark">✳</div><h2>{p.name}</h2><p>{p.description||'Your saved meeting setup.'}</p><div className="preset-meta"><span><Clock3 size={15}/>{p.durationMinutes} min</span><span><Users size={15}/>{p.capacity} seats</span></div><Button asChild className="full-width"><Link href={`/app/planner?duration=${p.durationMinutes}&capacity=${p.capacity}`}>Use this preset<ArrowUpRight size={16}/></Link></Button><div className="management-actions"><Button size="sm" variant="ghost" onClick={()=>setEditing(p)}><Pencil size={14}/>Edit</Button><Button size="sm" variant="ghost" onClick={()=>setRemove(p)}><Trash2 size={14}/>Delete</Button></div></CardContent></Card>)}</div>}
 {editing&&<PresetEditor item={editing==='new'?undefined:editing} onClose={()=>setEditing(null)} onSave={saved=>setItems(old=>[...old.filter(p=>p.id!==saved.id),saved])}/>}
 {remove&&<ConfirmAction title={`Delete ${remove.name}?`} description="This removes the saved setup. Existing room bookings are kept." label="Delete preset" onClose={()=>setRemove(null)} action={async()=>{await request(`/templates/${remove.id}`,{method:'DELETE'});setItems(old=>old.filter(p=>p.id!==remove.id));}}/>}</>;
}
function PresetEditor({item,onClose,onSave}:{item?:Preset;onClose:()=>void;onSave:(p:Preset)=>void}){const [busy,setBusy]=useState(false);const [error,setError]=useState('');return <Modal title={item?'Edit meeting preset':'A new recurring idea'} subtitle="Set the details once. Choose participants each time you use it." busy={busy} onClose={onClose}><form className="product-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const saved=await request<Preset>(item?`/templates/${item.id}`:'/templates',{method:item?'PUT':'POST',body:JSON.stringify({name:f.get('name'),description:f.get('description'),durationMinutes:Number(f.get('duration')),capacity:Number(f.get('capacity'))})});onSave(saved);onClose();}catch(e){setError(e instanceof Error?e.message:'Could not save preset.');}finally{setBusy(false);}}}><label>Preset name<Input name="name" required maxLength={100} defaultValue={item?.name} placeholder="A name that makes sense to your team"/></label><label>Description<Textarea name="description" maxLength={500} defaultValue={item?.description} placeholder="What is this time for?"/></label><div className="two-fields"><label>Duration (minutes)<Input name="duration" required type="number" min={15} max={480} defaultValue={item?.durationMinutes||30}/></label><label>Seats needed<Input name="capacity" required type="number" min={1} max={1000} defaultValue={item?.capacity||2}/></label></div>{error&&<p role="alert" className="form-error">{error}</p>}<Button type="submit" disabled={busy}>{busy?'Saving…':'Save preset'}</Button></form></Modal>;}
