"use client";
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { Check,ArrowUpRight,LoaderCircle } from 'lucide-react';
import { Card,CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { request } from '@/lib/api';
import type { Plan } from '@/lib/product';
import { useSession } from './session';
import { SiteText } from './site-provider';
import { PublicNav,PublicFooter } from './landing';
type Usage={plan:Plan;members:number;rooms:number;bookings:number;presets:number};
export function Pricing({embedded=false}:{embedded?:boolean}){
 const [plans,setPlans]=useState<Plan[]>([]);const [usage,setUsage]=useState<Usage|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState('');const {user,refresh}=useSession();
 useEffect(()=>{request<Plan[]>('/plans').then(setPlans).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(embedded&&user)request<Usage>('/tools/usage').then(setUsage).catch(e=>setError(e.message));},[embedded,user]);
 async function openBilling(id?:string){setBusy(id||'portal');setError('');try{const result=await request<{url:string}>(id?'/billing/checkout':'/billing/portal',{method:'POST',...(id?{body:JSON.stringify({plan:id})}:{})});window.location.assign(result.url);}catch(e){setError(e instanceof Error?e.message:'Billing unavailable.');}finally{setBusy('');}}
 return <div className={embedded?'pricing-embedded':'public-site'}>{!embedded&&<PublicNav/>}<section id="main-content" className="pricing-section"><span className="kicker">A LITTLE STRUCTURE. A LOT OF POSSIBILITY.</span><h1><SiteText name="pricing.heading"/></h1><p><SiteText name="pricing.intro"/></p>{error&&<p role="alert" className="form-error">{error}</p>}
 {embedded&&usage&&<div className="usage-summary"><div><strong>{user?.role==='ADMIN'?'Administrator workspace':usage.plan.name+' workspace'}</strong><span>{user?.role==='ADMIN'?'Administrative workspaces have no plan caps.':'Your current usage, updated from saved records.'}</span></div>{(['members','rooms','bookings','presets'] as const).map(key=><span key={key}><strong>{usage[key]}</strong> / {user?.role==='ADMIN'?'∞':usage.plan[key]} {key}</span>)}</div>}
 {!plans.length&&!error&&<p role="status">Loading plans…</p>}
 <div className="pricing-grid">{plans.map(plan=><Card key={plan.id} className={`pricing-card ${plan.id==='studio'?'featured-plan':''}`}><CardContent><div className="plan-label"><h2>{plan.name}</h2>{plan.id==='studio'&&<Badge>Room to grow</Badge>}</div><p>{plan.description}</p><div className="plan-price">{new Intl.NumberFormat(plan.currency==='INR'?'en-IN':'en-US',{style:'currency',currency:plan.currency,maximumFractionDigits:0}).format(plan.monthlyPrice)}<span>{plan.currency} / workspace / month</span></div><ul>{[`${plan.members} people in your directory`,`${plan.rooms} bookable rooms`,`${plan.bookings} active weekly reservations`,`${plan.presets} saved meeting presets`,'Availability matching & conflict checks','Bulk import, CSV & calendar export','Room utilization insights'].map(item=><li key={item}><Check size={15}/>{item}</li>)}</ul>
 {!user?<Button asChild variant={plan.id==='studio'?'default':'outline'} className="full-width"><Link href={`/signup?plan=${plan.id}`}>Explore {plan.name}<ArrowUpRight size={16}/></Link></Button>:user.plan===plan.id?<Button variant="outline" className="full-width" disabled>Current plan</Button>:<Button className="full-width" variant={plan.id==='studio'?'default':'outline'} disabled={!!busy||(!plan.checkoutEnabled&&user.plan==='free')} onClick={()=>void openBilling(user.plan==='free'?plan.id:undefined)}>{busy===plan.id&&<LoaderCircle size={15} className="spin"/>}{user.plan!=='free'?'Manage your plan':plan.checkoutEnabled?`Choose ${plan.name}`:'Checkout opening soon'}</Button>}
 </CardContent></Card>)}</div>
 <p className="pricing-footnote">Explore before subscribing: a preview workspace includes 5 people, 2 rooms, 10 weekly bookings, and 3 presets with no card required. The three paid plans expand those limits. Prices are monthly and exclude applicable taxes.</p>
 <div className="pricing-legal-links"><Link href="/refunds">Refunds & cancellation</Link><Link href="/terms">Terms</Link><Link href="/contact">Talk to us</Link></div>
 {embedded&&<div className="billing-tools">{user?.plan!=='free'&&<Button variant="outline" disabled={!!busy} onClick={()=>void openBilling()}>Manage payment & subscription</Button>}<Button variant="ghost" disabled={!!busy} onClick={()=>void refresh()}>Refresh plan status</Button><p>Subscription access updates after the payment provider confirms it. Existing records remain if you move to a smaller plan; adding more is subject to your new limits.</p></div>}
 <div className="pricing-faq"><h2>Choose the space you need.</h2><details><summary>Which plan fits my group?</summary><p>Gather is for a small club or team with a few spaces. Studio fits teams with several projects and rooms. Collective offers more capacity for busy community or shared-office coordination. All three include the core scheduling tools.</p></details><details><summary>Does each person get a login?</summary><p>Plan limits count the people whose availability you manage. Directory entries do not create logins or invitations. Each account has its own private workspace.</p></details><details><summary>Can I explore before paying?</summary><p>Yes. Create a preview workspace without a card, add your own records, and choose a paid plan when you need more capacity. Preview does not automatically become a paid subscription.</p></details><details><summary>Are bookings recurring?</summary><p>Yes. Availability and reservations repeat weekly. Calendar export produces recurring events in your workspace timezone.</p></details><details><summary>Can I change or cancel a plan?</summary><p>Use Plans & billing to open the subscription portal. Review its effective date before confirming a change. For billing help, visit our <Link href="/refunds">refunds and cancellation page</Link>.</p></details></div></section>{!embedded&&<PublicFooter/>}</div>;
}
