import Link from 'next/link';
import { ArrowRight, ArrowUpRight, BookOpen, CalendarDays, Cookie, CreditCard, DoorOpen, FileText, HeartHandshake, Mail, Phone, ShieldCheck, Sparkles, Users } from 'lucide-react';
import { PublicFooter, PublicNav } from './landing';
import { ContactComposer, HelpAnswers } from './support-tools';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { product } from '@/lib/product';
import { policies, policyUpdated, type Policy } from '@/lib/legal-content';

export const publicPages: Record<string, { title: string; description: string }> = {
  about: { title: 'About', description: `A thoughtful space for people, places, and shared time. Meet ${product.name}, in association with ${product.companyName}.` },
  contact: { title: 'Contact', description: `Contact ${product.name} for product support, billing, privacy, or partnerships. Email ${product.supportEmail} or call ${product.supportPhone}.` },
  help: { title: 'Help centre', description: 'Get started with your workspace, find meeting times, manage rooms, and understand subscriptions.' },
  legal: { title: 'Legal centre', description: 'Privacy, terms, cookies, refunds, security, and accessibility, together in one clear place.' },
  ...Object.fromEntries(Object.entries(policies).map(([slug, policy]) => [slug, { title: policy.title, description: policy.description }])),
};

function PageFrame({ children }: { children: React.ReactNode }) {
  return <div className="public-site"><PublicNav/><main id="main-content" className="information-main">{children}</main><PublicFooter/></div>;
}

function SupportNote() {
  return <section className="support-note"><div><span className="kicker">ALWAYS A WAY TO REACH US</span><h2>Some things deserve<br/><em>a conversation.</em></h2><p>A question, a suggestion, or something that needs a second look.<br/>We’d like to hear it.</p></div><Button asChild><Link href="/contact">Let’s talk <ArrowUpRight size={17}/></Link></Button><span className="support-note-art" aria-hidden="true">✳</span></section>;
}

function AboutPage() {
  return <PageFrame><section className="information-hero about-hero"><div><span className="eyebrow-pill"><i/>IN ASSOCIATION WITH {product.companyName.toUpperCase()}</span><h1>Time together.<br/><span className="serif-word">Well spent.</span></h1><p>A good idea needs people, a place, and a moment that works for everyone. {product.name} brings those pieces together.</p><Button asChild><Link href="/signup">Find your common ground<ArrowUpRight size={17}/></Link></Button></div><div className="about-art" aria-label="People, place, and time coming together"><span className="about-art-label">THE INGREDIENTS OF SOMETHING GOOD</span><div className="about-tile tile-lilac"><Users size={36}/><strong>Your people.</strong><span>A team worth making time for.</span></div><div className="about-tile tile-peach"><DoorOpen size={34}/><strong>Your place.</strong><span>Room for the next big idea.</span></div><div className="about-tile tile-mint"><CalendarDays size={29}/><strong>Your moment.</strong><span>Let’s make it happen.</span></div><span className="about-art-star" aria-hidden="true">✳</span></div></section>
    <section className="about-purpose"><div><span className="kicker">WHY THIS EXISTS</span><h2>Less coordination.<br/><em>More connection.</em></h2></div><div><p>“When is everyone free?” is only half the question. You also need a room that’s open, enough seats, and a way to keep the next meeting from becoming another long conversation about calendars.</p><p>{product.name} connects weekly availability with bookable spaces. It gives student communities, creative teams, shared offices, and small businesses a place to manage the practical details of getting together.</p><p>Your people, your room names, your rhythm. Every new workspace starts with room to make it your own.</p></div></section>
    <section className="about-values">{[{ icon: Users, title: 'Start with real people.', text: 'Manage your own team directory and availability. Use names, colours, and schedules that mean something to your group.', color: 'lilac' }, { icon: DoorOpen, title: 'Make every space count.', text: 'Keep room capacity, opening hours, reservations, and utilization in one place. Spot clashes before they become interruptions.', color: 'rose' }, { icon: Sparkles, title: 'Make good habits repeat.', text: 'Save meeting presets, reserve recurring times, and export calendar events. Spend less effort arranging the next session.', color: 'butter' }].map(({ icon: Icon, title, text, color }) => <Card className={`info-card ${color}`} key={title}><CardContent><Icon size={26}/><h3>{title}</h3><p>{text}</p></CardContent></Card>)}</section>
    <section className="company-panel"><span className="company-monogram" aria-hidden="true">S<span>✳</span></span><div><span className="kicker">A SHARED ASSOCIATION</span><h2>{product.name} × {product.companyName}</h2><p>{product.name} is associated with {product.companyName}. For company enquiries or a conversation about working together, visit the company website or contact us directly.</p><a href={product.companyUrl}>Visit {product.companyName}<ArrowUpRight size={16}/></a></div></section><SupportNote/></PageFrame>;
}

function ContactPage() {
  return <PageFrame><section className="information-hero compact-hero"><span className="eyebrow-pill"><i/>A HUMAN ON THE OTHER SIDE</span><h1>Good things start<br/><span className="serif-word">with a hello.</span></h1><p>Need a hand with your workspace? Have an idea for what comes next?<br/>You’re in the right place.</p></section><div className="contact-layout"><div className="contact-methods"><a className="contact-method lilac" href={`mailto:${product.supportEmail}`}><span className="contact-icon"><Mail size={23}/></span><span><small>WRITE TO US</small><strong>{product.supportEmail}</strong><span>Product, account, and billing enquiries</span></span><ArrowUpRight size={19}/></a><a className="contact-method rose" href={`tel:${product.supportPhone.replace(/[^+\d]/g, '')}`}><span className="contact-icon"><Phone size={23}/></span><span><small>GIVE US A CALL</small><strong>{product.supportPhone}</strong><span>Prefer a conversation? Reach out directly.</span></span><ArrowUpRight size={19}/></a><a className="contact-method butter" href={product.companyUrl}><span className="contact-icon"><HeartHandshake size={23}/></span><span><small>OUR ASSOCIATION</small><strong>{product.companyName}</strong><span>{product.companyUrl.replace(/^https?:\/\//, '').replace(/\/$/, '')}</span></span><ArrowUpRight size={19}/></a><div className="contact-side-note"><BookOpen size={21}/><h2>A quick answer might be here.</h2><p>From your first booking to timezones and billing, our help centre covers the essentials.</p><Link href="/help">Explore the help centre<ArrowRight size={15}/></Link></div></div><ContactComposer/></div><section className="contact-topics"><h2>Help us get to the right answer.</h2><div><article><span>01</span><h3>Product support</h3><p>Tell us the page, what you expected, and what happened. Include an error message if you have one.</p></article><article><span>02</span><h3>Billing or refunds</h3><p>Include your account email and payment reference. Please never share full card details.</p><Link href="/refunds">Billing guidance<ArrowUpRight size={14}/></Link></article><article><span>03</span><h3>Privacy or security</h3><p>Use “Privacy request” or “Security report” in the subject, and leave sensitive data out of attachments.</p><Link href="/security">Report a concern<ArrowUpRight size={14}/></Link></article></div></section></PageFrame>;
}

function HelpPage() {
  return <PageFrame><section className="information-hero compact-hero"><span className="eyebrow-pill"><i/>A LITTLE GUIDANCE GOES A LONG WAY</span><h1>Less figuring out.<br/><span className="serif-word">More getting going.</span></h1><p>Get comfortable with your workspace, one good question at a time.</p></section><section className="help-start-cards" aria-label="Getting started steps">{[{ icon: Users, n: '01', title: 'Bring your people.', text: 'Add your directory and weekly availability.', href: '/app/planner' }, { icon: DoorOpen, n: '02', title: 'Make some room.', text: 'Add spaces, seats, and opening hours.', href: '/app/rooms' }, { icon: CalendarDays, n: '03', title: 'Find your moment.', text: 'Match a time, reserve a room, and export.', href: '/app/planner' }].map(({ icon: Icon, n, title, text, href }) => <Link href={href} key={n}><div><Icon size={24}/><span>{n}</span></div><h2>{title}</h2><p>{text}</p><ArrowUpRight size={17}/></Link>)}</section><HelpAnswers/><SupportNote/></PageFrame>;
}

const policyIcons = { privacy: ShieldCheck, terms: FileText, refunds: CreditCard, cookies: Cookie, security: ShieldCheck, accessibility: HeartHandshake };

function LegalIndex() {
  return <PageFrame><section className="information-hero compact-hero"><span className="eyebrow-pill"><i/>THE DETAILS, WITHOUT THE GUESSWORK</span><h1>A little clarity.<br/><span className="serif-word">A lot of trust.</span></h1><p>Understand how {product.name} works, how information is handled,<br/>and where to turn when you need help.</p></section><section className="legal-index-grid" aria-label="Policies and service information">{Object.entries(policies).map(([slug, policy], index) => { const Icon = policyIcons[slug as keyof typeof policyIcons]; return <Link href={`/${slug}`} key={slug} className={`legal-index-card policy-colour-${index % 3}`}><div><span><Icon size={25}/></span><ArrowUpRight size={20}/></div><h2>{policy.title}</h2><p>{policy.description}</p><small>Read the details <ArrowRight size={14}/></small></Link>; })}</section><div className="legal-association"><ShieldCheck size={22}/><p>{product.name} is associated with <a href={product.companyUrl}>{product.companyName}</a>. For a question about any of these pages, <Link href="/contact">contact us directly</Link>.</p></div><SupportNote/></PageFrame>;
}

function PolicyPage({ policy }: { policy: Policy }) {
  return <PageFrame><section className="policy-hero"><Link href="/legal" className="policy-back">← All policies & information</Link><span className="kicker">CLEAR WORDS. SHARED UNDERSTANDING.</span><h1>{policy.title}</h1><p>{policy.description}</p><span className="policy-date">Last updated <time dateTime="2026-09-29">{policyUpdated}</time></span></section><div className="policy-layout"><aside className="policy-sidebar"><nav aria-label="On this page"><span className="kicker">ON THIS PAGE</span>{policy.sections.map((section, index) => <a key={section.id} href={`#${section.id}`}><span>{String(index + 1).padStart(2, '0')}</span>{section.title}</a>)}</nav><div className="policy-help"><Mail size={21}/><strong>A question about this?</strong><p>There’s a real person to contact.</p><Link href="/contact">Get in touch<ArrowUpRight size={14}/></Link></div></aside><article className="policy-document"><div className="policy-summary"><span aria-hidden="true">✳</span><p>{policy.summary}</p></div>{policy.sections.map((section, index) => <section id={section.id} key={section.id}><span className="policy-section-number">{String(index + 1).padStart(2, '0')}</span><h2>{section.title}</h2>{section.paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}{section.points && <ul>{section.points.map(point => <li key={point}>{point}</li>)}</ul>}</section>)}<div className="policy-document-end"><span>In association with <a href={product.companyUrl}>{product.companyName}</a></span><Link href="/contact">Questions? Let’s talk<ArrowUpRight size={14}/></Link></div></article></div></PageFrame>;
}

export function InformationPage({ page }: { page: string }) {
  if (page === 'about') return <AboutPage/>;
  if (page === 'contact') return <ContactPage/>;
  if (page === 'help') return <HelpPage/>;
  if (page === 'legal') return <LegalIndex/>;
  return <PolicyPage policy={policies[page]}/>;
}
