'use client';
import { useEffect,useState } from 'react';
import { useRouter } from 'next/navigation';
import { Dialog } from 'radix-ui';
import { Search,ArrowUpRight,X } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { useSession } from './session';
const actions=[['Overview','Your workspace and next steps','/app'],['Plan a meeting','Find a time and room for your team','/app/planner'],['Spaces & rooms','Add or edit a room','/app/rooms'],['Bookings','Manage reservations and export calendar','/app/bookings'],['Meeting presets','Save a reusable meeting setup','/app/presets'],['Bulk import people','Paste names and preview before importing','/app/import'],['Export workspace','Download your data and spreadsheets','/app/export'],['Insights','Studio: scheduled room utilization','/app/insights'],['Operations reports','Collective: weekday heatmap, free slots and reports','/app/operations'],['Plans & billing','Compare plans or manage subscription','/app/billing'],['Settings','Your name, workspace, and timezone','/app/settings'],['Help centre','Search answers to common questions','/help'],['Contact','Get in touch with support','/contact']];
export function QuickActions(){
 const [open,setOpen]=useState(false);const [query,setQuery]=useState('');const [selected,setSelected]=useState(0);const router=useRouter();const {user}=useSession();
 const matches=[...actions,...(user?.role==='ADMIN'?[['Administration','Content, accounts, pricing, and audit log','/app/admin']]:[])].filter(item=>item.join(' ').toLowerCase().includes(query.toLowerCase()));
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setOpen(v=>!v);setQuery('');setSelected(0);}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[]);
 function go(href:string){setOpen(false);router.push(href);}
 return <Dialog.Root open={open} onOpenChange={value=>{setOpen(value);setQuery('');setSelected(0);}}><Dialog.Trigger asChild><button className="command-trigger" aria-label="Open command menu"><Search size={16}/><span>Quick actions</span><kbd>Ctrl / ⌘ K</kbd></button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="command-overlay"/><Dialog.Content className="command-dialog"><Dialog.Title className="sr-only">Quick actions</Dialog.Title><Dialog.Description className="sr-only">Search pages, then use arrow keys and Enter to open a result.</Dialog.Description><div className="command-search"><Search size={20}/><Input autoFocus placeholder="Where would you like to go?" value={query} onChange={e=>{setQuery(e.target.value);setSelected(0);}} role="combobox" aria-expanded="true" aria-controls="command-results" aria-autocomplete="list" aria-activedescendant={matches.length?`command-${selected}`:undefined} onKeyDown={e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();setSelected(i=>matches.length?(i+(e.key==='ArrowDown'?1:-1)+matches.length)%matches.length:0);}if(e.key==='Enter'&&matches[selected]){e.preventDefault();go(matches[selected][2]);}}}/><Dialog.Close aria-label="Close command menu"><X size={18}/></Dialog.Close></div><div id="command-results" className="command-results" role="listbox" aria-label="Pages and actions">{matches.map(([title,detail,href],i)=><button id={`command-${i}`} role="option" aria-selected={selected===i} tabIndex={-1} className={selected===i?'selected':''} key={href} onMouseMove={()=>setSelected(i)} onClick={()=>go(href)}><span><strong>{title}</strong><small>{detail}</small></span><ArrowUpRight size={17}/></button>)}{!matches.length&&<p>No matching action. Try “rooms”, “import”, or “help”.</p>}</div><div className="command-hint">↑ ↓ to explore <span>Enter to open · Esc to close</span></div></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
