'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight,Download,Upload,Users,Check,LoaderCircle } from 'lucide-react';
import { api,request } from '@/lib/api';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Card,CardContent } from '@/components/ui/card';
import type { Member,Room,Booking } from '@/lib/types';
import type { Account,Preset } from '@/lib/product';
import { useSession } from './session';
type ExportData={schemaVersion:number;exportedAt:string;workspace:Account;members:Member[];rooms:Room[];bookings:Booking[];presets:Preset[]};
function download(contents:string,type:string,name:string){const url=URL.createObjectURL(new Blob([contents],{type}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}
function csv(rows:(string|number)[][]){return '\uFEFF'+rows.map(row=>row.map(value=>{let text=String(value);if(/^[\s]*[=+@-]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"';}).join(',')).join('\r\n');}
export function WorkspaceTools({mode='index'}:{mode?:'index'|'import'|'export'}){
 const {user}=useSession();const [names,setNames]=useState('');const [existing,setExisting]=useState<Member[]>([]);const [loading,setLoading]=useState(mode==='import');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 useEffect(()=>{if(mode!=='import')return;let active=true;api.members().then(data=>{if(active)setExisting(data);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[mode]);
 const seen=new Set(existing.map(m=>m.name.trim().toLowerCase()));const proposed=names.split(/\r?\n/).map(n=>n.trim()).filter(Boolean);const fresh:string[]=[];let skipped=0;
 for(const name of proposed){if(seen.has(name.toLowerCase()))skipped++;else{fresh.push(name);seen.add(name.toLowerCase());}}
 const invalid=fresh.some(n=>n.length>80)||fresh.length>100;
 async function importNames(){setBusy(true);setError('');setMessage('');try{const added=await request<Member[]>('/tools/import-members',{method:'POST',body:JSON.stringify({names:fresh})});setExisting(old=>[...old,...added]);setNames('');setMessage(`${added.length} people added. Set their availability in the planner when you’re ready.`);}catch(e){setError(e instanceof Error?e.message:'Import failed.');try{setExisting(await api.members());}catch{}}finally{setBusy(false);}}
 async function exportData(format:'json'|'people'|'rooms'|'bookings'){setBusy(true);setError('');setMessage('');try{const data=await request<ExportData>('/tools/export');const date=new Date().toISOString().slice(0,10);if(format==='json')download(JSON.stringify(data,null,2),'application/json',`workspace-${date}.json`);else{const rows: (string|number)[][]=format==='people'?[['Name','Colour','Day','Available from','Available until'],...data.members.flatMap(m=>m.availability.length?m.availability.map(a=>[m.name,m.color,a.dayOfWeek,a.startTime,a.endTime]):[[m.name,m.color,'','','']])]:format==='rooms'?[['Room','Location','Capacity','Opens','Closes'],...data.rooms.map(r=>[r.name,r.location,r.capacity,r.openTime,r.closeTime])]:[['Room','Day','Start','End','Timezone','Repeats'],...data.bookings.map(b=>[b.roomName,b.dayOfWeek,b.startTime,b.endTime,user?.timezone||'UTC','Weekly'])];download(csv(rows),'text/csv;charset=utf-8',`${format}-${date}.csv`);}setMessage('Your export has been prepared for download.');}catch(e){setError(e instanceof Error?e.message:'Export failed.');}finally{setBusy(false);}}
 return <><div className="page-heading"><div><span className="kicker">THE LITTLE THINGS, MADE EASIER</span><h1>{mode==='import'?'Bring everyone along.':mode==='export'?'Your data, to go.':'Less admin. More momentum.'}</h1><p>{mode==='import'?'Paste one person per line. Review the list, then import together.':mode==='export'?'Download a fresh copy of your own workspace.':'Practical tools that give a little time back to your day.'}</p></div></div>{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="success-note" role="status"><Check size={16}/>{message}</p>}
 {mode==='index'&&<div className="tool-grid">{[['/app/import','Bulk import people','Bring in a team list without adding each person individually.',Upload],['/app/export','Export your workspace','Download your records as JSON or a spreadsheet.',Download],['/app/presets','Meeting presets','Keep a useful meeting setup ready for next time.',Users]].map(([href,title,body,Icon])=>{const Symbol=Icon as typeof Upload;return <Link key={String(href)} href={String(href)} className="tool-card"><Symbol size={28}/><h2>{String(title)}</h2><p>{String(body)}</p><span>Open tool<ArrowUpRight size={17}/></span></Link>;})}</div>}
 {mode==='import'&&<div className="import-layout"><Card><CardContent><h2>Your team list</h2><form className="product-form" onSubmit={e=>{e.preventDefault();void importNames();}}><Label htmlFor="import-names">Names · one per line</Label><Textarea id="import-names" value={names} onChange={e=>{setNames(e.target.value);setError('');setMessage('');}} rows={10} maxLength={10000} placeholder="Paste your own list of names here" disabled={busy}/><small className="field-note">Up to 100 names per import, 80 characters per name. Existing names and duplicates are skipped. New people start without availability; no invitations are sent.</small><Button disabled={loading||busy||invalid||!fresh.length} type="submit">{busy?<LoaderCircle size={16} className="spin"/>:<Upload size={16}/>}Add {fresh.length} {fresh.length===1?'person':'people'}</Button></form></CardContent></Card><Card className="import-preview"><CardContent><span className="kicker">REVIEW BEFORE ADDING</span><h2>{fresh.length} new people</h2><p>{loading?'Loading your existing directory…':`${skipped} duplicate or existing names skipped.`}</p>{invalid&&<p className="form-error">Keep the list to 100 names and each name to 80 characters.</p>}<ul>{fresh.map((name,i)=><li key={name}><span>{i+1}</span>{name}</li>)}</ul>{!fresh.length&&<p>New names will appear here as you type.</p>}<Link href="/app/planner">Open people & availability<ArrowUpRight size={15}/></Link></CardContent></Card></div>}
 {mode==='export'&&<><div className="tool-grid">{[['json','Workspace JSON','People, availability, rooms, bookings, presets, and your profile.'],['people','People spreadsheet','A row for each weekly availability interval.'],['rooms','Rooms spreadsheet','Room names, locations, capacity, and hours.'],['bookings','Bookings spreadsheet','Weekly reservations with your workspace timezone.']].map(([format,title,body])=><Card key={format} className="export-card"><CardContent><Download size={26}/><h2>{title}</h2><p>{body}</p><Button variant="outline" disabled={busy} onClick={()=>void exportData(format as 'json'|'people'|'rooms'|'bookings')}>Download {format==='json'?'JSON':'CSV'}</Button></CardContent></Card>)}</div><p className="tool-note">Exports contain the information in your workspace. Keep downloaded copies private. JSON is a portable snapshot; automatic restore is not currently available. For calendar files, use <Link href="/app/bookings">Bookings → Export calendar</Link>.</p></>}
 </>;
}
