import { product } from './product';

export type Policy = {
  title: string;
  description: string;
  summary: string;
  sections: { id: string; title: string; paragraphs: string[]; points?: string[] }[];
};

export const policyUpdated = '30 September 2026';
export const policies: Record<string, Policy> = {
  privacy: {
    title: 'Privacy policy',
    description: 'What information the service uses, why it needs it, and how to ask for help with your data.',
    summary: 'Your workspace holds the information you add to coordinate people and places. It is not a public directory.',
    sections: [
      { id: 'who-we-are', title: 'Who this policy covers', paragraphs: [`This policy describes ${product.name}, a scheduling application associated with ${product.companyName}. For privacy questions or requests, contact ${product.supportEmail}. The contact page also lists our telephone number and company website.`] },
      { id: 'information', title: 'Information used by the service', paragraphs: ['We use information you provide to create your account and operate your workspace. Please only enter information you are entitled to share.'], points: ['Account details: your name, email address, password hash, workspace name, timezone, and selected plan. Your password is hashed rather than stored as readable text.', 'Workspace records: member names and colours, weekly availability, room details and opening hours, reservations, and saved meeting presets.', 'Billing details, when paid billing is enabled: payment-provider customer and subscription identifiers and subscription events. Card details are entered with the payment provider; the application does not store full card numbers.', 'Support correspondence you choose to send. Our contact composer prepares an email in your email application; it does not submit a message to a separate website form service.', 'Session information and operational records needed to serve requests. Hosting infrastructure may record request times, IP addresses, browser information, and errors.'] },
      { id: 'purpose', title: 'How information is used', paragraphs: ['Information is used to authenticate your account, show your workspace, match availability with room capacity, prevent conflicting reservations, enforce plan limits, and respond to support requests. Subscription information is used to reconcile access with your payment-provider subscription.', 'The application does not include advertising trackers or a feature that sells workspace information. Workspace insights calculate room utilization from your reservations; they do not measure attendance or monitor participants.'] },
      { id: 'sharing', title: 'Service providers and sharing', paragraphs: ['Hosting and database providers process information needed to run the service. When paid checkout is available, Stripe processes payments under its own privacy terms. Brevo delivers account verification and password-reset messages. Clerk processes social authentication identities when you choose social sign-in. Email and telephone providers also handle communications you initiate.', 'Authorised site administrators can manage account profile information, roles, status, site content, and plan limits; administrative changes are recorded. The application separates workspace records by account. Adding a person to your directory does not create an account, invite them, email them, or give them access. Information may also need to be disclosed to meet an applicable legal obligation or address abuse.'] },
      { id: 'storage', title: 'Storage and retention', paragraphs: ['Workspace records persist until removed through available controls or handled through a support request. Cancelling a reservation or removing a room changes operational records; signing out or cancelling a subscription does not automatically delete your account.', 'There is currently no automatic account-expiry or fixed data-retention schedule in the application. Logs, backups, support correspondence, and billing records may follow separate provider or operational retention schedules. Contact us for details about a specific record or to request deletion.'] },
      { id: 'choices', title: 'Your choices and requests', paragraphs: [`You can edit your profile, workspace name, timezone, people, availability, rooms, and presets in the application, and export your workspace records from Workspace tools. To request access, correction, a copy, or deletion of other information, email ${product.supportEmail} with the subject “Privacy request”. If a workspace owner added your information, identify the workspace and record involved.`, 'We may need to verify your identity or authority before handling a request. Do not send passwords or full payment-card details. Applicable legal rights are not limited by this policy. Some records may need to be retained to meet legal obligations or resolve a dispute.'] },
      { id: 'cookies-security', title: 'Cookies and account protection', paragraphs: ['An essential session cookie keeps you signed in. The application uses password hashing, account-scoped access checks, and protections for state-changing browser requests. These measures do not remove every security risk. See our Cookie policy and Security page for more detail.'] },
      { id: 'changes', title: 'Changes and concerns', paragraphs: [`The date above identifies this version. This policy should be updated when the service’s data practices change. For an unresolved privacy concern, contact ${product.supportEmail}; any rights to contact an appropriate authority remain available under applicable law.`] },
    ],
  },
  terms: {
    title: 'Terms of service',
    description: 'The working agreement for accounts, workspace content, scheduling, and subscriptions.',
    summary: 'Use your workspace responsibly, keep account access private, and check a reservation before relying on it.',
    sections: [
      { id: 'service', title: 'The service and these terms', paragraphs: [`${product.name} is a scheduling service associated with ${product.companyName}. It helps an account owner manage people, weekly availability, spaces, and recurring reservations. These terms describe the conditions for using the service. If you act for an organisation, you must have authority to use the service and provide its information.`] },
      { id: 'account', title: 'Your account', paragraphs: ['Provide accurate account information and keep your password private. You are responsible for activities you authorise through your account. Contact us if you suspect unauthorised access. A directory entry is a scheduling record, not an invitation or a separate user account.', 'Use the service only if you can enter a binding agreement under the rules that apply to you. The service is not designed to collect information about children without the necessary authority or permissions.'] },
      { id: 'content', title: 'Your workspace information', paragraphs: ['You retain your rights in the information you add. You give the service permission to process that information as needed to provide its scheduling, storage, support, and billing functions.', 'Only add people and information you have a legitimate reason and authority to manage. Keep records accurate and avoid unnecessary sensitive information. Do not upload unlawful content, misuse another person’s information, interfere with the service, or try to access another account’s records.'] },
      { id: 'scheduling', title: 'How scheduling works', paragraphs: ['Availability and reservations repeat weekly. Room opening hours currently apply every day. Times use the workspace timezone. Changing the timezone relabels existing wall-clock schedules rather than shifting them to a new instant.', 'Results depend on the information entered. A reservation in this application does not establish ownership of a physical room or notify a building operator. Confirm any external permissions you need. Calendar export produces a file for you to import; it does not provide ongoing two-way calendar synchronization.'] },
      { id: 'plans', title: 'Plans, payments, and limits', paragraphs: ['The pricing page describes available limits and displayed monthly prices. A free workspace does not require a payment card. Paid checkout is available only when billing has been enabled.', 'Review the currency, recurring amount, taxes if applicable, and renewal terms shown at checkout before purchasing. The payment provider’s checkout records describe the transaction you authorise. Subscription access follows the subscription status reported by the provider. Do not complete checkout if the displayed details differ from what you expected; contact us instead.', 'The Refunds & cancellation page explains how to request help or manage a subscription. A plan change does not automatically delete existing workspace records. Limits may prevent adding further records until usage is within the applicable plan.'] },
      { id: 'availability', title: 'Availability and changes', paragraphs: ['Features may change as the service develops, and interruptions can occur. The service does not include a contractual uptime or response-time commitment unless separately agreed in writing. Keep copies of information that is important to your operations.', 'Access may need to be restricted to address misuse, a security incident, or a legal requirement. Contact support if you believe access has been restricted incorrectly.'] },
      { id: 'responsibility', title: 'Responsibilities and legal rights', paragraphs: ['Use the service with appropriate care for your circumstances. Scheduling results cannot guarantee that people attend, a physical space is ready, or a business outcome is achieved.', 'Nothing in these terms removes rights or remedies that cannot lawfully be excluded. Responsibility for a dispute is determined by applicable law and any binding agreement for your purchase. These terms do not assert a particular court or jurisdiction.'] },
      { id: 'contact', title: 'Questions and updates', paragraphs: [`For questions about these terms, account access, or a dispute, contact ${product.supportEmail}. The version date is shown above. Review updated terms when changes are brought to your attention, especially before starting or renewing a paid subscription.`] },
    ],
  },
  refunds: {
    title: 'Refunds & cancellation',
    description: 'Clear next steps for subscription changes, billing questions, and refund requests.',
    summary: 'You can start free. If you purchase a subscription, keep your checkout receipt and use billing support for any payment concern.',
    sections: [
      { id: 'free', title: 'Free workspaces', paragraphs: ['Creating a free workspace does not require a card and does not start a paid subscription. A disabled paid-plan button does not charge you or put you on a subscription.'] },
      { id: 'subscriptions', title: 'Before a paid purchase', paragraphs: ['Paid billing is available only when checkout is enabled. Review the recurring price, currency, taxes if applicable, renewal details, and any purchase-specific cancellation or refund terms displayed at checkout. Keep the receipt from the payment provider.', 'No universal money-back period or automatic refund entitlement is advertised by this application. Your purchase-specific terms and mandatory consumer rights continue to apply.'] },
      { id: 'cancel', title: 'Manage or cancel a subscription', paragraphs: ['For an active subscription, open Plans & billing in your workspace and choose the billing portal. Available cancellation and plan-change options depend on the payment provider’s portal configuration. Read the effective date and confirmation shown there.', `If the portal is unavailable or you cannot access your account, email ${product.supportEmail} with your account email and subscription reference. A cancellation request sent by email requires review; sending the email alone is not confirmation that cancellation has completed.`, 'Cancelling billing does not automatically delete your workspace. Your plan follows the subscription status received from the payment provider. Contact support separately if you also want account or data deletion.'] },
      { id: 'refund-request', title: 'Request a refund or report an error', paragraphs: [`Email ${product.supportEmail} with the subject “Billing or refund request”. Include the account email, payment date, amount and currency, receipt or transaction reference, and a brief description of the issue. Do not include your password or full card number.`, 'Requests are reviewed against the purchase terms, payment records, and applicable law. Approval, amount, and processing time are not guaranteed by this page. Where a refund is approved, its settlement time depends on the payment provider and your bank.'] },
      { id: 'rights', title: 'Your rights', paragraphs: ['This page does not limit any cancellation, refund, or dispute rights that apply under mandatory law. If you believe a charge is unauthorised, contact us and your payment provider promptly.'] },
    ],
  },
  cookies: {
    title: 'Cookie policy',
    description: 'A straightforward explanation of the browser storage used to keep your workspace signed in.',
    summary: 'The application uses an essential session cookie. It currently has no advertising or third-party analytics scripts.',
    sections: [
      { id: 'session', title: 'The essential session cookie', paragraphs: ['The session cookie, normally named JSESSIONID, allows the server to recognise your signed-in session and associate requests with the correct account. It also supports the session state used to protect changes to your workspace.', 'It is an HttpOnly cookie, so application scripts cannot read its value. It is created as part of session and authentication requests and uses SameSite=Lax. The HTTPS-only Secure attribute depends on the hosting configuration.'] },
      { id: 'lifetime', title: 'How long it lasts', paragraphs: ['The cookie is a browser-session cookie rather than a long-lived advertising identifier. Server sessions expire after the configured inactivity timeout, and signing out invalidates the session. Browser session-restoration settings may preserve session cookies when reopening a browser.', 'Sessions are currently held by the backend process, so a backend restart may require you to sign in again.'] },
      { id: 'other-services', title: 'Other storage and external services', paragraphs: ['The current application does not install advertising cookies or a third-party analytics library. Fonts are served with the application. Workspace insights are calculated from reservations rather than third-party tracking.', 'The installable app caches its public offline page and icons, never workspace API responses or private pages. Redis holds temporary authentication sessions and abuse-prevention counters. Clerk may set essential sign-in cookies on social-authentication pages. Your browser may cache static assets. Following an external company link, opening an email application, or entering the payment provider’s checkout or portal takes you to a separate service with its own storage and privacy practices. Hosting providers may apply additional operational cookies or protections according to their configuration.'] },
      { id: 'choices', title: 'Your browser controls', paragraphs: ['You can clear or block cookies in your browser settings. Blocking the essential session cookie prevents normal sign-in and authenticated workspace operations. Clearing browser cookies does not delete records stored in your account.', `For cookie or data questions, contact ${product.supportEmail}. See the Privacy policy for requests involving account information.`] },
    ],
  },
  security: {
    title: 'Security',
    description: 'How account protection works today, and a direct route to report a concern.',
    summary: 'Clear protection, honest boundaries, and a human contact when something needs attention.',
    sections: [
      { id: 'account-protection', title: 'Protecting account access', paragraphs: ['The backend uses Spring Security with hashed passwords and server-managed sessions. An HttpOnly session cookie identifies signed-in requests. State-changing browser requests require a CSRF token.', 'Workspace records are scoped to the signed-in account. Billing subscription events are checked using the payment provider’s webhook signature before changing plan access. These controls reduce risk; they are not a guarantee that incidents cannot happen.'] },
      { id: 'your-part', title: 'Keeping your workspace safe', paragraphs: ['Use a unique password and keep access to your account email secure. Sign out on shared devices and only add information needed for coordination. Never share your password, session cookie, or payment-card details in a support message.', 'Email verification and password recovery use expiring, single-use email links. Password changes revoke existing sessions. Social sign-in is available through Clerk when configured. Collaborator invitations are not currently available.'] },
      { id: 'report', title: 'Report a security concern', paragraphs: [`Email ${product.supportEmail} with the subject “Security report — ${product.name}”. Include the affected page or endpoint, a brief explanation, and safe reproduction steps. Remove personal information, credentials, and session tokens from screenshots and logs.`, 'Please avoid accessing another person’s information, disrupting the service, or publishing sensitive details while reporting an issue. This page does not establish a paid bug-bounty programme or grant permission for intrusive testing.'] },
      { id: 'assurance', title: 'Scope of these statements', paragraphs: ['This page describes application controls. It does not claim independent certification, a completed external security audit, guaranteed uptime, or immunity from attacks. Hosting, transport encryption, database access, backups, and operational response also depend on the environment running the application.'] },
    ],
  },
  accessibility: {
    title: 'Accessibility',
    description: 'Making room for different ways of using the web, and improving with your feedback.',
    summary: 'People should be able to find a time together without the interface getting in their way.',
    sections: [
      { id: 'design', title: 'How the interface is built', paragraphs: ['The interface uses labelled form controls, visible focus states, text labels alongside important icons, and responsive layouts. Public pages include a skip-to-content link, and the help centre uses native expandable sections.', 'Motion effects respect the device’s reduced-motion setting. Availability is described with text as well as colour. You can use your browser’s zoom controls to increase content size.'] },
      { id: 'scope', title: 'An ongoing effort', paragraphs: ['Accessibility is an ongoing part of improving the application. We have not completed an independent accessibility audit and do not claim conformance to a particular accessibility standard. Some scheduling controls may still be more difficult to use with certain assistive technologies.'] },
      { id: 'feedback', title: 'Tell us what gets in your way', paragraphs: [`Contact ${product.supportEmail} or call ${product.supportPhone} if you encounter a barrier. Include the page address, what you were trying to do, and your browser or assistive technology if you are comfortable sharing it. Avoid including private workspace information.`, 'You can use the same contact details to ask for help understanding information on the site. Feedback helps identify what needs attention.'] },
    ],
  },
};
