import { product } from './product';
export const siteFields = [
 ['Brand','brand.name','Product name',product.name],['Brand','brand.tagline','Tagline',product.tagline],['Brand','brand.supportEmail','Support email',product.supportEmail],['Brand','brand.supportPhone','Phone',product.supportPhone],['Brand','brand.companyName','Company name',product.companyName],['Brand','brand.companyUrl','Company website',product.companyUrl],
 ['Homepage','home.eyebrow','Eyebrow','A LITTLE LESS “WHEN ARE YOU FREE?”'],['Homepage','home.heading','Main heading','Less back-and-forth.'],['Homepage','home.emphasis','Emphasis','More getting together.'],['Homepage','home.description','Introduction','Turn everyone’s availability into a time and a place. One thoughtful workspace for people who do things together.'],['Homepage','home.cta','Primary button','Make room for your team'],
 ['Homepage','home.feature1.title','People card heading','Start with your people.'],['Homepage','home.feature1.body','People card text','Add anyone, set their weekly availability, and pick the people joining this meeting.'],['Homepage','home.feature2.title','Spaces card heading','Make space for ideas.'],['Homepage','home.feature2.body','Spaces card text','Name your rooms. Set their hours and seats. Keep every reservation in one place.'],['Homepage','home.feature3.title','Planner card heading','Meet in the middle.'],['Homepage','home.feature3.body','Planner card text','Find a time and room that fit everyone. Book it, export it, or save the setup for next time.'],
 ['Pages','page.about.heading','About heading','Time together.'],['Pages','page.about.emphasis','About emphasis','Well spent.'],['Pages','page.about.intro','About introduction','A good idea needs people, a place, and a moment that works for everyone. MeetGrid brings those pieces together.'],
 ['Pages','page.contact.heading','Contact heading','Good things start'],['Pages','page.contact.emphasis','Contact emphasis','with a hello.'],['Pages','page.contact.intro','Contact introduction','Need a hand with your workspace? Have an idea for what comes next? You’re in the right place.'],
 ['Pages','page.help.heading','Help heading','Less figuring out.'],['Pages','page.help.emphasis','Help emphasis','More getting going.'],['Pages','page.help.intro','Help introduction','Get comfortable with your workspace, one good question at a time.'],
 ['Pages','page.legal.heading','Legal heading','A little clarity.'],['Pages','page.legal.emphasis','Legal emphasis','A lot of trust.'],['Pages','page.legal.intro','Legal introduction','Understand how MeetGrid works, how information is handled, and where to turn when you need help.'],
 ['Pages','page.how.heading','How it works heading','From “when?” to booked.'],['Pages','page.how.intro','How it works introduction','One workflow for the people, time, and place. Make a recurring meeting work for everyone.'],
 ['Pages','page.usecases.heading','Use cases heading','A place for your kind of together.'],['Pages','page.usecases.intro','Use cases introduction','Practical coordination for teams, clubs, studios, and shared spaces.'],
 ['Pricing','pricing.heading','Pricing heading','A small price for a calmer week.'],['Pricing','pricing.intro','Pricing introduction','Three monthly plans. Pick the room your team needs to grow.'],
] as const;
export const defaultCopy:Record<string,string> = Object.fromEntries(siteFields.map(([,key,,value])=>[key,value]));
export type SiteSnapshot = {version:number;values:Record<string,string>};
